### ISSUE TITLE
Translate Japanese into English

### ISSUE THREAD

**Issue by sano-jin** [sano-jin/express-beamer#2]

**Comment by colin4124** [comment]
If this work have done, I would like to translate English to Chinese.

**Comment by rbstrachan** [comment]
@sano-jinさん
おはようございます！

どの文書を日本語から英語に翻訳する必要がありますか？

よろしくお願いします

**Comment by sano-jin** [comment]
@rbstrachan  さん，こんにちは！

> どの文書を日本語から英語に翻訳する必要がありますか？

https://github.com/sano-jin/express-beamer/tree/main/tex
にある tex ファイルの中身（これがソースコードで，ここから出力 https://github.com/sano-jin/express-beamer/blob/main/slide.pdf を得ます）です．
現状，これが唯一の documentation なので，まずはこれをさっさとなんとかしないとなと思っています．

が，なかなか時間が取れなくて，まだ手をつけられていません．．．😭
